export const SPORTS_LIST = [
  {
    id: '족구',
    name: '족구',
    englishName: 'Jokgu',
    emoji: '⚽',
    subEmoji: '👟',
    color: 'emerald',
    badgeBg: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    cardBg: 'bg-gradient-to-br from-emerald-50 to-teal-50/40 border-emerald-200',
    accentColor: '#10b981',
    headerBg: 'bg-emerald-500',
    bannerGradient: 'from-emerald-500 to-teal-600',
    iconBg: 'bg-emerald-100 text-emerald-600',
    defaultPlayersCount: 6,
    description: '발과 머리로 네트를 넘기는 전통 스포츠!',
  },
  {
    id: '배구',
    name: '배구',
    englishName: 'Volleyball',
    emoji: '🏐',
    subEmoji: '✨',
    color: 'sky',
    badgeBg: 'bg-sky-100 text-sky-800 border-sky-300',
    cardBg: 'bg-gradient-to-br from-sky-50 to-blue-50/40 border-sky-200',
    accentColor: '#0284c7',
    headerBg: 'bg-sky-500',
    bannerGradient: 'from-sky-500 to-blue-600',
    iconBg: 'bg-sky-100 text-sky-600',
    defaultPlayersCount: 9,
    description: '스파이크와 토스로 팀워크를 다지는 경기!',
  },
  {
    id: '농구',
    name: '농구',
    englishName: 'Basketball',
    emoji: '🏀',
    subEmoji: '🔥',
    color: 'orange',
    badgeBg: 'bg-orange-100 text-orange-800 border-orange-300',
    cardBg: 'bg-gradient-to-br from-orange-50 to-amber-50/40 border-orange-200',
    accentColor: '#f97316',
    headerBg: 'bg-orange-500',
    bannerGradient: 'from-orange-500 to-amber-600',
    iconBg: 'bg-orange-100 text-orange-600',
    defaultPlayersCount: 5,
    description: '골밑을 향해 달리는 열정의 코트!',
  },
  {
    id: '플라잉디스크',
    name: '플라잉디스크',
    englishName: 'Flying Disc',
    emoji: '🥏',
    subEmoji: '🌈',
    color: 'violet',
    badgeBg: 'bg-violet-100 text-violet-800 border-violet-300',
    cardBg: 'bg-gradient-to-br from-violet-50 to-purple-50/40 border-violet-200',
    accentColor: '#8b5cf6',
    headerBg: 'bg-violet-500',
    bannerGradient: 'from-violet-500 to-purple-600',
    iconBg: 'bg-violet-100 text-violet-600',
    defaultPlayersCount: 7,
    description: '하늘을 가르는 원반 얼티미트 & 윷놀이!',
  },
  {
    id: '배드민턴',
    name: '배드민턴',
    englishName: 'Badminton',
    emoji: '🏸',
    subEmoji: '💨',
    color: 'pink',
    badgeBg: 'bg-pink-100 text-pink-800 border-pink-300',
    cardBg: 'bg-gradient-to-br from-pink-50 to-rose-50/40 border-pink-200',
    accentColor: '#ec4899',
    headerBg: 'bg-pink-500',
    bannerGradient: 'from-pink-500 to-rose-600',
    iconBg: 'bg-pink-100 text-pink-600',
    defaultPlayersCount: 4,
    description: '날렵한 스매시와 빠른 랠리의 매력!',
  },
  {
    id: '티볼',
    name: '티볼',
    englishName: 'Tee-Ball',
    emoji: '⚾',
    subEmoji: '🧢',
    color: 'amber',
    badgeBg: 'bg-amber-100 text-amber-800 border-amber-300',
    cardBg: 'bg-gradient-to-br from-amber-50 to-yellow-50/40 border-amber-200',
    accentColor: '#d97706',
    headerBg: 'bg-amber-500',
    bannerGradient: 'from-amber-500 to-yellow-600',
    iconBg: 'bg-amber-100 text-amber-600',
    defaultPlayersCount: 10,
    description: '홈런을 향해 힘차게 배트를 휘두르자!',
  },
];

export const getSportConfig = (sportName) => {
  return SPORTS_LIST.find((s) => s.name === sportName) || {
    id: '기타',
    name: sportName || '기타',
    englishName: 'Sports',
    emoji: '🏆',
    subEmoji: '⭐',
    color: 'slate',
    badgeBg: 'bg-slate-100 text-slate-800 border-slate-300',
    cardBg: 'bg-white border-slate-200',
    accentColor: '#64748b',
    headerBg: 'bg-slate-600',
    bannerGradient: 'from-slate-600 to-slate-700',
    iconBg: 'bg-slate-100 text-slate-600',
    defaultPlayersCount: 5,
    description: '학생스포츠클럽 대회',
  };
};
